unstable_features = true
edition = "2024"

max_width = 120
newline_style = "Unix"
hard_tabs = true

group_imports = "StdExternalCrate"
imports_layout = "HorizontalVertical"
imports_granularity = "Module"

wrap_comments = true

use_small_heuristics = "Max"
